---
- hosts: all
  tasks:
  - name: creating multiple files at a time
    file:
      path: /opt/{{item}}
      state: touch
    with_items:
          - sum.java
          - name.all
          - data.state

