---
- hosts: all 
  tasks:
    - name: creating a file with contents
      copy:
        dest: /opt/sum-2-numbers.py
        content:
          num1 = 15;
          num2 = 12;
          sum = num1 + num2;
          print("sum of {0} and {1} is {2}" .format(num1, num2, sum));
